[package]
name = "server_monitor"
version = "0.1.0"
authors = ["Xijezu <xijezu@ngemity.org>"]

[dependencies]
rust-ini = "0.13"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
mysql = "*"